@startuml AppFlowy
title Plugin Design
left to right direction
skinparam linetype polyline

package "Plugin-Sandbox"  #DDDDDD {
    component [Plugin API] as plugin_api #F7931E
    component [Plugin Proxy] as plugin_proxy #F7931E
    component [Plugin Service] as plugin_service #F7931E
    component [Plugin Runner] as plugin_runner #F7931E
    component [Plugin] as plugin #F7931E
}

package Plugin-Host #DDDDDD {
    package "Front-end (Flutter)" {
        component [Plugin Repository] as plugin_repo #00B5FF
        component [Flowy Document] as document #00B5FF
    }

    package "Back-end (Rust)" {
        node "Plugin Module" as plugin_module #00B5FF {
            component [Plugin Event] as plugin_event #00B5FF
            component [Plugin Service] as plugin_rust_service #00B5FF
        }
    }
}

plugin_runner ..> plugin_service
plugin_service .> plugin
plugin .> plugin_proxy
plugin_proxy .> plugin_api
plugin_api ..> plugin_repo
plugin_repo ..> plugin_event : FFI
plugin_event .> plugin_rust_service

plugin --o document
@enduml


@startuml AppFlowy
title Plugins
left to right direction
skinparam linetype polyline

component FlowyDocument #00B5FF

component FlutterQuillPlugin as text_plugin #0CA789 {
}

component GridPlugin as grid_plugin #0CA789 {
}

component CalendarPlugin as cal_plugin #0CA789 {
}

component KanbanPlugin as kanban_plugin #0CA789 {
}

component Plugin as plugin #F7931E {
}

plugin --o FlowyDocument

text_plugin ..|> plugin
grid_plugin ..|> plugin
cal_plugin ..|> plugin
kanban_plugin ..|> plugin
@enduml


@startuml AppFlowy
title Plugin Classes
left to right direction
skinparam linetype polyline

interface PluginAPI {
   fn set_data(data: PluginData);
   fn get_data() -> PluginData;
}
class PluginRepository
class PluginProxy
class PluginService
class Plugin {
}
class FlutterQuillPlugin
class GridQuillPlugin

FlutterQuillPlugin --|> Plugin
GridQuillPlugin --|> Plugin

class PluginRunner
class MacOSPluginRunner
class iOSPluginRunner
class WebPluginRunner

MacOSPluginRunner --|> PluginRunner
iOSPluginRunner --|> PluginRunner
WebPluginRunner --|> PluginRunner

PluginRunner -> PluginService
PluginService -> Plugin
Plugin -> PluginProxy
PluginProxy -> PluginAPI
PluginAPI <|.. PluginRepository


@enduml


@startuml AppFlowy
title flowy-sync
left to right direction

class BlockManager {}
interface BlockCloudService {
}

interface RevisionWebSocket {}
class BlockEditors {}
interface BlockUser {}
class ClientBlockEditor #F7931E {}
class ClientFolderEditor #00B5FF {}

BlockManager --> BlockCloudService
BlockManager --> RevisionWebSocket: own
BlockManager --> BlockEditors
BlockManager --> BlockUser

BlockEditors "1" *-- "*" ClientBlockEditor
BlockHttpCloudService .u.|> BlockCloudService
LocalServer .u.|> BlockCloudService
BlockUserImpl .u.|> BlockUser
BlockUserImpl --> UserSession

class RevisionManager {}
class RevisionWebSocketManager {}
class EditorCommandSender {}
interface RevisionCloudService {}
ClientBlockEditor --> RevisionManager
ClientBlockEditor --> RevisionWebSocketManager
ClientBlockEditor --> EditorCommandSender

ClientFolderEditor --> RevisionManager
ClientFolderEditor --> RevisionWebSocketManager

RevisionManager ..> RevisionLoader
RevisionLoader --> RevisionCloudService

class RevisionPersistence {}
interface RevisionWSDataIterator {}
interface RevisionWSDataStream {}
class FolderWSDataSink #00B5FF {}
class FolderWebSocket #00B5FF {}
class FolderRevisionWSDataStream #00B5FF {}
class FolderConflictResolver #00B5FF {}
class FolderRevisionCloudService #00B5FF

class BlockWSDataSink #F7931E {}
class BlockWebSocket #F7931E {}
class BlockRevisionWSDataStream #F7931E {}
class BlockConflictResolver #F7931E {}
class BlockRevisionCloudService #F7931E


RevisionManager --> RevisionPersistence
RevisionWebSocketManager --> RevisionWSDataIterator
RevisionWebSocketManager --> RevisionWSDataStream
RevisionWebSocketManager -u-> RevisionWebSocket

FolderWSDataSink .u.|> RevisionWSDataIterator
BlockWSDataSink .u.|> RevisionWSDataIterator
FolderWSDataSink --> WSDataProvider
BlockWSDataSink --> WSDataProvider

BlockWebSocket .u.|> RevisionWebSocket
FolderWebSocket .u.|> RevisionWebSocket

BlockRevisionCloudService .u.|> RevisionCloudService
FolderRevisionCloudService .u.|> RevisionCloudService

BlockRevisionWSDataStream .u.|> RevisionWSDataStream
FolderRevisionWSDataStream .U.|> RevisionWSDataStream
BlockRevisionWSDataStream --> ConflictController
FolderRevisionWSDataStream --> ConflictController

interface ConflictResolver {}
interface ConflictRevisionSink {}
interface WSDataProviderDataSource {}
ConflictController --> ConflictResolver
ConflictController --> ConflictRevisionSink
BlockConflictResolver .u.|> ConflictResolver
FolderConflictResolver .u.|> ConflictResolver
WSDataProvider ..|> ConflictRevisionSink
WSDataProvider -l-> WSDataProviderDataSource
RevisionManager ..|> WSDataProviderDataSource

interface RevisionDiskCache {}
class RevisionMemoryCache {}
class RevisionSyncSequence {}
RevisionPersistence -d-> RevisionDiskCache
RevisionPersistence -d-> RevisionMemoryCache
RevisionPersistence -d-> RevisionSyncSequence

class SQLitePersistence {}
SQLitePersistence .u.|> RevisionDiskCache
@enduml



@startuml
node "Plugin Runner" as plugin_runner {
   component [iOS] #F7931E
   component [Android] #F7931E
   component [Linux] #F7931E
   component [macOS] #F7931E
   component [Windows] #F7931E
   component [Web] #F7931E
}

node Plugins #DDDDDD {
    component "FlutterQuill" #FB006D
    component "Kanban" #FB006D
    component "Grid" #FB006D
    component "Calendar" #FB006D
}

package FlowyDocument #00B5FF [
        Plugin
    ....
        Plugin
    ....
        Plugin
    ....
        Plugin
]

@enduml


@startuml AppFlowy
title Plugin Design2
left to right direction
skinparam linetype polyline

package "Front-end (Flutter)" #DDDDDD {
    component [Plugin Repository] as plugin_repo #00B5FF
    component [Flowy Document] as document #00B5FF
    node "Plugin-Sandbox"  {
        component [Plugin API] as plugin_api #F7931E
        component [Plugin Proxy] as plugin_proxy #F7931E
        component [Plugin Service] as plugin_service #F7931E
        component [Plugin Runner] as plugin_runner #F7931E
        component [Plugin] as plugin #F7931E
    }
}

package "Back-end (Rust)" #DDDDDD {
    node "Plugin Module" as plugin_module #00B5FF {
        component [Plugin Event] as plugin_event #00B5FF
        component [Plugin Service] as plugin_rust_service #00B5FF
    }
}

plugin_runner ..> plugin_service
plugin_service .> plugin
plugin .> plugin_proxy
plugin_proxy .> plugin_api
plugin_api ..> plugin_repo
plugin_repo ..> plugin_event : FFI
plugin_event .> plugin_rust_service

plugin --o document
@enduml