@startuml DDDOperationFlow
title DDD - Operation Flow
' left to right direction
skinparam linetype ortho

package Presentation as "Presentation Layer" {
    class Widget
}

package Application as "Application Layer" {
    rectangle Bloc {
        class Event as "Event"
        class StateClass as "State"
    }
}

package Domain as "Domain Layer" {
    rectangle DataModel as "Data Model"{
        class Aggregate as "Aggregate"
        class EntityClass as "Entity"
        class ValueObject as "Value Object"
    }
    class Service as "Service"
    interface RepositoryInterface as "Repository Interface"
}

package Infrastructure as "Infrastructure Layer" {
    class NetworkService as "Network Service"
    class PersistenceService as "Persistence Service"
    class UnitOfWork as "Unit Of Work"
    class RepositoryImplementation as "Repository Implementation"
}


user -[hidden]right- Presentation
Presentation -[hidden]right- Application
Application -[hidden]right- Domain
Domain -[hidden]right- Infrastructure

user --> Widget

' Presentation Layer
Event -[hidden]right-> StateClass
Widget --> Event : "1"

' Application Layer
StateClass --> Widget : 7
Bloc -> RepositoryInterface : 3
Bloc -> DataModel : 2

' Domain Layer
Aggregate -[hidden]-> EntityClass
EntityClass -[hidden]-> ValueObject
DataModel *-- Service
DataModel --> RepositoryInterface

' Infrastructure Layer
RepositoryImplementation ..|> RepositoryInterface
RepositoryImplementation --> UnitOfWork : "4"
UnitOfWork --> PersistenceService : "5"
PersistenceService --> NetworkService : "6"
RepositoryImplementation -> DataModel


' |#dee4e8|User|
' |#dee4e8|Presentation|
' |#c4c9cd|Application|
' |#daf0fe|Domain|
' |#daf0fe|Infrastructure|

' |User|
' start
' |Presentation|
'    :Widget;
'    |Application|
'      :Bloc Event;
'      split
'         |Domain|
'         :Data Model;
'         |Application|
'         :Bloc State;
'         |Presentation|
'         :Widget;
'      detach
'      split again
'         |Infrastructure|
'         :Interface;
'         :Unit of Work;
'         :Persistence Service;
'      stop
'      end split




@enduml
