left to right direction
skinparam linetype ortho

@startuml DDDBLoCPattern
participant user
box "Presentation" #DDDDDD
participant Widget
end box
box "Application" #AAAAAA
participant Bloc
end box

title DDD - BLoC Pattern
user -> Widget
activate Widget

Widget -> Bloc:Event
activate Bloc

Bloc -> Widget: State
deactivate Bloc
@enduml
