@startuml DDDRepositoryImplementsInterface
title DDD - Repository Implements Interface
left to right direction
skinparam linetype ortho

component Domain {
    interface IAuthentication {
        login();
        logout();
    }

    interface IInterface {
        methodA();
        methodB();
    }
}

component Infrastructure {
    class Authentication {
        login() {...};
        logout() {...};
    }

    class Implementation {
        methodA() {...};
        methodB() {...};
    }
}

IAuthentication <|.. Authentication
IInterface <|.. Implementation
@enduml
