@startuml EditorFlutterQuill

left to right direction
skinparam linetype ortho

title Editor (FlutterQuill)

package Widget <<Rectangle>> {
    class RenderObjectWidget
    class EditableTextLine
    class TextLine
    class Line

    note as N3
    Widget : holds the config 
    for a piece of UI.
    end note
}


package Element <<Rectangle>> {
    class _TextLineElement
    class RenderObjectElement
    
    note as N1
    Represents an actual
    piece of UI.
    end note
}


package RenderObject <<Rectangle>>  {
    class RenderEditableTextLine
    class RenderEditableBox
    class RenderBox
    class RenderObjectClass as "RenderObject"

    note as N2
    Layout, size, painting
    and compositing
    end note
}

Element -[hidden]-> RenderObject

EditableTextLine -> RenderObjectWidget
EditableTextLine -left> TextLine
EditableTextLine -left> Line

RenderObjectWidget <-- _TextLineElement
_TextLineElement -left> RenderObjectElement
_TextLineElement -> RenderEditableTextLine
' RenderEditableTextLine <-right- _TextLineElement

RenderEditableTextLine -left> RenderEditableBox
RenderEditableBox -left> RenderBox
RenderBox -left> RenderObjectClass

@enduml
