@startuml EventDispatchFrontend
title Event Dispatch - Frontend
left to right direction
skinparam linetype ortho


package "Frontend" #DDDDDD {
    component Widget_A as "Widget A"
    component Widget_B as "Widget B"
    component Widget_C as "Widget ..."
    component Bloc_A as "Bloc A"
    component Bloc_B as "Bloc B"
    component Bloc_C as "Bloc ..."
    component Repository_A as "Repository A"
    component Repository_B as "Repository B"
    component Repository_C as "Repository ..."
    component Event
    component FFI_Frontend as "FFI" #FFDDDD
}

Widget_C --> Bloc_C : 1
Widget_B --> Bloc_B : 1
Widget_A --> Bloc_A : 1
Bloc_C  --> Repository_C : 2
Bloc_B  --> Repository_B : 2
Bloc_A  --> Repository_A : 2
Repository_C --> Event : 3
Repository_B --> Event : 3
Repository_A --> Event : 3

Event --> FFI_Frontend : 4
@enduml
