@startuml Structure 
left to right direction
' top to bottom direction

class View
note bottom of View: Component

class "NonEmbedableBlock"  as leaf #DDDDDD {
    List<EmbedableBlock> children
}
note top of leaf: Leaf, Blocks can not be added

Class "EmbedableBlock" as group
note top of group: Group, Blocks can be added

Class "Page" as App
Class "TextBlock" as TextBlock

Workspace *-- App
App --|> group
View <|-- leaf
View <|-- group
View --* group
leaf <|-- TextBlock
TextBlock *-- Quill
leaf <|-- CalendarBlock
leaf <|-- SpreadsheetBlock
leaf <|-- TodoBlock
leaf <|-- ImageBlock
leaf <|-- MusicPlayerBlock
group <|-- Column
group <|-- Row
' EmbedebleBlock <|-- App
' View <|-- App
@enduml


@startuml StructureBack 
class View
class Leaf #DDDDDD
User *-- Workspace
Workspace *-- App 
Workspace *-- App2 
Workspace *-- App3
App *-- View
View *-- Block
Block --> Block
Block --> View 
App *-- View2
View *-- View 
View2 *-- View2
View2 *-- Block2
Block2 *-- Block2
Block2 *-- View2
App3 *-- View3
View3 <|-- NonEmbedableBlock
View3 <|-- EmbedebleBlock 
View3 --* EmbedebleBlock
@enduml