@startuml DDDLayeredArchitecture
title DDD - Layered Architecture A
left to right direction
skinparam linetype ortho

class TableAggregate
class Table {
    String : id,
    String : desc,
}

Class "Row" {
    String: table_id
}

TableAggregate *-- Table
Table *-- Row
@enduml

@startuml DDDLayeredArchitectureB
title DDD - Layered Architecture B
left to right direction
skinparam linetype ortho

class TableAggregate {
    List<Row> : rows
    Table : table
}
class Table {
    String : id,
    String : desc,
}

Class "Row" {
    String: table_id
}

TableAggregate "1"*-right-"1" Table
TableAggregate "many"*--"1" Row


@enduml
