
@startuml SelectOption
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

class SelectOptionService
class SelectOptionCellEditorBloc

SelectOptionCellEditorBloc --> SelectOptionService
SelectOptionCellEditorBloc --> GridSelectOptionCellController

@enduml


@startuml CellData
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface IGridCellDataLoader
interface IGridCellDataConfig
interface IGridCellDataPersistence
interface IGridCellController
interface ICellDataParser

GridCellController --|> IGridCellController
GridSelectOptionCellController --|> IGridCellController
GridURLCellController --|> IGridCellController
GridDateCellController --|> IGridCellController

IGridCellController --> GridCell

'Data config
IGridCellDataLoader --> IGridCellDataConfig
GridCellDataConfig -u-|> IGridCellDataConfig

'Data loader
IGridCellController --> IGridCellDataLoader
GridCellDataLoader -u-|> IGridCellDataLoader
GridCellDataLoader --> ICellDataParser

'Data parser
StringCellDataParser -u-|> ICellDataParser
DateCellDataParser -u-|> ICellDataParser
SelectOptionCellDataParser -u-|> ICellDataParser
URLCellDataParser -u-|> ICellDataParser

'Cache
IGridCellController --> GridCellsCache


'Persistence
IGridCellController --> IGridCellDataPersistence
DateCellDataPersistence -u-|> IGridCellDataPersistence
CellDataPersistence -u-|> IGridCellDataPersistence


'Field
IGridCellController --> GridCellFieldNotifier

@enduml