openapi: "3.0.2"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
info:
  title: AppFlowy REST API
  version: 1.0.0
servers:
  - url: https://beta.appflowy.cloud
paths:
  /gotrue/token:
    $ref: './paths/gotrue_token.yaml'
  /web-api/oauth-redirect/token:
    $ref: './paths/oauth_redirect_token.yaml'
  /api/workspace:
    $ref: './paths/workspace.yaml'
  /api/workspace/{workspace_id}/database:
    $ref: './paths/database.yaml'
  /api/workspace/{workspace_id}/folder:
    $ref: './paths/workspace_folder.yaml'
  /api/workspace/{workspace_id}/database/{database_id}/fields:
    $ref: './paths/database_fields.yaml'
  /api/workspace/{workspace_id}/database/{database_id}/row:
    $ref: './paths/database_row.yaml'
  /api/workspace/{workspace_id}/database/{database_id}/row/updated:
    $ref: './paths/database_row_updated.yaml'
  /api/workspace/{workspace_id}/database/{database_id}/row/detail:
    $ref: './paths/database_row_detail.yaml'
