openapi: "3.0.2"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
info:
  title: AppFlowy REST API
  version: 1.0.0
servers:
  - url: https://beta.appflowy.cloud/api
paths:
  /workspace:
    $ref: './paths/workspace.yaml'
  /workspace/{workspace_id}/database:
    $ref: './paths/database.yaml'
  /workspace/{workspace_id}/database/{database_id}/fields:
    $ref: './paths/database_fields.yaml'
  /workspace/{workspace_id}/database/{database_id}/row:
    $ref: './paths/database_row.yaml'
  /workspace//{workspace_id}/database/{database_id}/row/updated:
    $ref: './paths/database_row_updated.yaml'
  /workspace/{workspace_id}/database/{database_id}/row/detail:
    $ref: './paths/database_row_detail.yaml'
