@startuml
title Events

package "Frontend" #DDDDDD {
    component Events
}

package "Backend" #DDDDDD {
    component FlowyCore
}

FlowyCore <-l- Events
@enduml

@startuml
title Notifications

package "Frontend" #DDDDDD {
    component Notifications
}

package "Backend" #DDDDDD {
    component FlowyCore
}

Notifications <-r- FlowyCore
@enduml
