@startuml
title Events

package "Frontend" #DDDDDD {
    component Events
}

package "Backend" #DDDDDD {
    component EventHandler as "Event Handler"
}

EventHandler <-l- Events: Protobuf
@enduml

@startuml
title Notifications

package "Frontend" #DDDDDD {
    component Notifications
}

package "Backend" #DDDDDD {
    component EventHandler as "Event Handler"
}

Notifications <-r- EventHandler: Protobuf
@enduml
