
@startuml AppFlowy
title Editor Classes
skinparam classFontStyle Bold

left to right direction

'Revision
'    classes
    class RevisionManager {}
    class RevisionWebSocketManager {}
    class RevisionPersistence {}
    class RevisionMemoryCache {}
    class RevisionSyncSequence {}


'    interface
    interface RevisionWebSocket {}
    interface RevisionCloudService {}
    interface RevisionWebSocketSink {}
    interface RevisionWSDataStream {}
    interface RevisionDiskCache {}

'    interface impl
    RevisionManager ..|> WSDataProviderDataSource

'   websocket
    RevisionWebSocketManager --> RevisionWebSocketSink
    RevisionWebSocketManager --> RevisionWSDataStream
    RevisionWebSocketManager --> RevisionWebSocket

'   deps
    RevisionManager ..> RevisionLoader
    RevisionLoader --> RevisionCloudService
    RevisionLoader -->RevisionPersistence
    RevisionManager --> RevisionPersistence
    RevisionPersistence -d-> RevisionDiskCache
    RevisionPersistence -d-> RevisionMemoryCache
    RevisionPersistence -d-> RevisionSyncSequence

'Folder
'    classes
    class FolderEditor #00B5FF {}
    class FolderWSDataSink #00B5FF {}
    class FolderWebSocket #00B5FF {}
    class FolderRevisionWSDataStream #00B5FF {}
    class FolderConflictResolver #00B5FF {}
    class FolderRevisionCloudService #00B5FF
    class SQLiteFolderRevisionPersistence #00B5FF  {}

'   interface impl
    SQLiteFolderRevisionPersistence .u.|> RevisionDiskCache
    FolderConflictResolver .u.|> ConflictResolver

'    websocket
    FolderRevisionWSDataStream .U.|> RevisionWSDataStream
    FolderRevisionWSDataStream --> ConflictController
    FolderWebSocket .u.|> RevisionWebSocket
    FolderWSDataSink .u.|> RevisionWebSocketSink
    FolderWSDataSink --> WSDataProvider

'   deps
    FolderEditor --> RevisionManager
    FolderEditor --> RevisionWebSocketManager
    FolderRevisionCloudService .u.|> RevisionCloudService

'TextBlock
'   classes
    class TextBlockEditor #F7931E {}
    class TextBlockWSDataSink #F7931E {}
    class TextBlockWebSocket #F7931E {}
    class TextBlockRevisionWSDataStream #F7931E {}
    class TextBlockConflictResolver #F7931E {}
    class TextBlockRevisionCloudService #F7931E
    class SQLiteTextBlockRevisionPersistence #F7931E {}

'   interface impl
    SQLiteTextBlockRevisionPersistence .u.|> RevisionDiskCache
    TextBlockConflictResolver .u.|> ConflictResolver

'    websocket
    TextBlockRevisionWSDataStream .u.|> RevisionWSDataStream
    TextBlockRevisionWSDataStream --> ConflictController
    TextBlockWebSocket .u.|> RevisionWebSocket
    TextBlockWSDataSink .u.|> RevisionWebSocketSink
    TextBlockWSDataSink --> WSDataProvider

'   deps
    TextBlockEditor --> RevisionManager
    TextBlockEditor --> RevisionWebSocketManager
    TextBlockRevisionCloudService .u.|> RevisionCloudService

'Grid
'   classes
    class GridRevisionEditor #FB006D
    class GridBlockRevisionEditor #CEE741
    class GridRevisionCloudService #FB006D
    class GridBlockRevisionCloudService #CEE741
    class SQLiteGridRevisionPersistence #FB006D {}
    class SQLiteGridBlockRevisionPersistence #CEE741 {}

'   interface impl
    SQLiteGridRevisionPersistence .u.|> RevisionDiskCache
    SQLiteGridBlockRevisionPersistence .u.|> RevisionDiskCache

'   deps
    GridRevisionEditor --> RevisionManager
    GridRevisionEditor --> RevisionWebSocketManager
    GridRevisionEditor -l-> GridBlockRevisionEditor
    GridBlockRevisionEditor --> RevisionManager
    GridBlockRevisionEditor --> RevisionWebSocketManager
    GridRevisionCloudService .u.|> RevisionCloudService
    GridBlockRevisionCloudService .u.|> RevisionCloudService


'History
'   classes
    class RevisionHistoryManager {}

'   interface
    interface RevisionHistoryDiskCache {}

'   interface impl
    SQLiteRevisionHistoryPersistence .u.|> RevisionHistoryDiskCache

'   deps
    RevisionManager ..> RevisionHistoryManager
    RevisionHistoryManager ..> RevisionHistoryConfig
    RevisionHistoryManager ..> RevisionHistoryDiskCache

'Snapshot
'   interface
    interface RevisionSnapshotDiskCache {}

'   interface impl
    SQLiteRevisionSnapshotPersistence .u.|> RevisionSnapshotDiskCache

'   deps
    RevisionManager ..> RevisionSnapshotManager
    RevisionSnapshotManager ..> RevisionSnapshotConfig
    RevisionSnapshotManager ..> RevisionSnapshotDiskCache


interface ConflictResolver {}
interface ConflictRevisionSink {}
interface WSDataProviderDataSource {}
ConflictController --> ConflictResolver
ConflictController --> ConflictRevisionSink

WSDataProvider ..|> ConflictRevisionSink
WSDataProvider -l-> WSDataProviderDataSource
@enduml



@startuml AppFlowy
title Block Editor Classes
left to right direction

class BlockManager {}
interface BlockCloudService {
}

interface RevisionWebSocket {}
class BlockEditors {}
interface BlockUser {}
class TextBlockEditor #F7931E {}

BlockManager --> BlockCloudService
BlockManager --> RevisionWebSocket: own
BlockManager --> BlockEditors
BlockManager --> BlockUser

BlockEditors "1" *-- "*" TextBlockEditor
BlockHttpCloudService .u.|> BlockCloudService
LocalServer .u.|> BlockCloudService
BlockUserImpl .u.|> BlockUser
BlockUserImpl --> UserSession

@enduml
