


@startuml Grid Cell Builder
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface GridCellWidget
GridCellBuilder --> GridCellWidget

GridSingleSelectCell -u-|> GridCellWidget
GridMultiSelectCell -u-|> GridCellWidget
GridDateCell -u-|> GridCellWidget
GridURLCell -u-|> GridCellWidget
GridCheckboxCell -u-|> GridCellWidget
GridNumberCell -u-|> GridCellWidget
GridTextCell -u-|> GridCellWidget

@enduml


@startuml Grid Selection Cell Edit
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

class SelectOptionService
class SelectOptionCellEditorBloc

GridSingleSelectCell --> SelectOptionCellEditor
SelectOptionCellEditor --> SelectOptionCellEditorBloc

SelectOptionCellEditorBloc --> SelectOptionService
SelectOptionCellEditorBloc --> GridSelectOptionCellController



@enduml


@startuml Grid Cell Controller
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface IGridCellDataPersistence
interface IGridCellController
interface IGridCellDataParser
interface TypeOptionDataParser

IGridCellController --> GridCellIdentifier
IGridCellController --> CellListener
IGridCellController --> TypeOptionDataParser

'Data loader
IGridCellController --> GridCellDataLoader
GridCellDataLoader --> IGridCellDataParser
GridCellDataLoader --> CellService

'Data parser
StringCellDataParser -u-|> IGridCellDataParser
DateCellDataParser -u-|> IGridCellDataParser
SelectOptionCellDataParser -u-|> IGridCellDataParser
URLCellDataParser -u-|> IGridCellDataParser

'Cache
IGridCellController --> GridCellCache


'Persistence
IGridCellController --> IGridCellDataPersistence
DateCellDataPersistence -u-|> IGridCellDataPersistence
CellDataPersistence -u-|> IGridCellDataPersistence

DateCellDataPersistence --> CellService
CellDataPersistence --> CellService

'Field
IGridCellController --> GridCellFieldNotifier

@enduml
