
@startuml Field Editor
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface IFieldTypeOptionLoader
interface TypeOptionWidgetContext

FieldEditor --> FieldEditorBloc
FieldEditor --> FieldTypeOptionEditor

'loader
FieldEditorBloc --> TypeOptionDataController
TypeOptionDataController --> IFieldTypeOptionLoader: own
NewFieldTypeOptionLoader -u-|> IFieldTypeOptionLoader
FieldTypeOptionLoader -u-|> IFieldTypeOptionLoader

'editor
FieldTypeOptionEditor --> FieldTypeOptionEditBloc
FieldTypeOptionEditor --> TypeOptionWidgetContext
FieldTypeOptionEditor ..> TypeOptionWidgetBuilder

'Context
TypeOptionWidgetContext -l-> TypeOptionDataController
@enduml

@startuml Field Type Option Widget Builder
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface TypeOptionWidgetContext
interface TypeOptionDataParser
interface IFieldTypeOptionLoader

TypeOptionWidgetContext --> TypeOptionDataController
TypeOptionDataController --> IFieldTypeOptionLoader
TypeOptionWidgetContext --> TypeOptionDataParser
@enduml

@startuml Field Type Option Widget Builder Impl
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction


DateTypeOptionWidgetBuilder -u-|> TypeOptionWidgetBuilder

NumberTypeOptionWidgetBuilder -u-|> TypeOptionWidgetBuilder

SingleSelectTypeOptionWidgetBuilder -u-|> TypeOptionWidgetBuilder

MultiSelectTypeOptionWidgetBuilder -u-|> TypeOptionWidgetBuilder

RichTextTypeOptionWidgetBuilder -u-|> TypeOptionWidgetBuilder

URLTypeOptionWidgetBuilder -u-|> TypeOptionWidgetBuilder

@enduml


@startuml Field Type Option Editor Data Parser
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface TypeOptionWidgetContext
interface TypeOptionDataParser


'type option builder
CheckboxTypeOptionContext --|> TypeOptionWidgetContext

DateTypeOptionContext --|> TypeOptionWidgetContext

NumberTypeOptionContext --|> TypeOptionWidgetContext

SingleSelectTypeOptionContext --|> TypeOptionWidgetContext

MultiSelectTypeOptionContext --|> TypeOptionWidgetContext


RichTextTypeOptionContext --|> TypeOptionWidgetContext

URLTypeOptionContext --|> TypeOptionWidgetContext

TypeOptionWidgetContext --> TypeOptionDataParser
DateTypeOptionDataParser -u-|> TypeOptionDataParser
MultiSelectTypeOptionDataParser -u-|> TypeOptionDataParser
NumberTypeOptionDataParser -u-|> TypeOptionDataParser
SingleSelectTypeOptionDataParser -u-|> TypeOptionDataParser
CheckboxTypeOptionDataParser -u-|> TypeOptionDataParser
RichTextTypeOptionDataParser -u-|> TypeOptionDataParser
URLTypeOptionDataParser -u-|> TypeOptionDataParser
@enduml

