


@startuml Grid Cell Builder
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface GridCellWidget
GridCellBuilder --> GridCellWidget

GridSingleSelectCell -u-|> GridCellWidget
GridMultiSelectCell -u-|> GridCellWidget
GridDateCell -u-|> GridCellWidget
GridURLCell -u-|> GridCellWidget
GridCheckboxCell -u-|> GridCellWidget
GridNumberCell -u-|> GridCellWidget
GridTextCell -u-|> GridCellWidget

@enduml


@startuml Grid Selection Cell Edit
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

class SelectOptionService
class SelectOptionCellEditorBloc

GridSingleSelectCell --> SelectOptionCellEditor
SelectOptionCellEditor --> SelectOptionCellEditorBloc

SelectOptionCellEditorBloc --> SelectOptionService
SelectOptionCellEditorBloc --> GridSelectOptionCellController



@enduml


@startuml Grid Cell Controller
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface GridCellDataPersistence
interface GridCellController
interface GridCellDataParser
interface TypeOptionDataParser

GridCellController --> GridCellIdentifier
GridCellController --> CellListener
GridCellController --> TypeOptionDataParser

'Data loader
GridCellController --> GridCellDataLoader
GridCellDataLoader --> GridCellDataParser
GridCellDataLoader --> CellService

'Data parser
StringCellDataParser -u-|> GridCellDataParser
DateCellDataParser -u-|> GridCellDataParser
SelectOptionCellDataParser -u-|> GridCellDataParser
URLCellDataParser -u-|> GridCellDataParser

'Cache
GridCellController --> GridCellCache


'Persistence
GridCellController --> GridCellDataPersistence
DateCellDataPersistence -u-|> GridCellDataPersistence
CellDataPersistence -u-|> GridCellDataPersistence

DateCellDataPersistence --> CellService
CellDataPersistence --> CellService

'Field
GridCellController --> GridCellFieldNotifier

@enduml
