@startuml
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

GridPB  "1" *-- "*" GridRowPB
GridPB  "1" *-- "*" GridFieldPB

@enduml