@startuml Grid
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

GridBloc --> GridController
GridController --> GridFFIService: own
GridController --> GridFieldController: own
GridController --> GridViewCache: own

GridFieldController --> GridFieldsListener: own
GridFieldController --> SettingListener: own
GridFieldController --> FiltersListener: own
GridFieldController --> GridFFIService: own
GridFieldController --> SettingFFIService: own
GridFieldController --> FilterFFIService: own

GridViewCache --> GridRowCache: own
GridViewCache --> GridViewListener: own

@enduml


@startuml row/cell relation
skinparam classFontStyle Bold
skinparam ActivityBackgroundColor Silver
skinparam ActivityBorderColor DimGray
left to right direction

interface RowCacheDelegate {
List<FieldInfo> get fields;
void onRowDispose();
}
class GridRowCache
class GridCellCache


'Row Cache
GridRowCache --> GridCellCache: own
GridRowCache --> RowChangesetNotifierForward
GridRowCache --> RowChangesetNotifier: own
GridRowCache --> RowCacheDelegate
GridRowCache --> RowList: own


RowList "1" *-- "*" RowInfo
RowInfo --> RowPB
RowInfo "1" o-- "*" FieldInfo


'Cell Cache
GridCellCache "1" *-- "*" GridCell
GridCellCache --> GridCellCacheKey



@enduml